### ISSUE TITLE
Create a minimal BTC->USDT exchange process

### ISSUE THREAD

**Issue by mentiflectax** [mentiflectax/minimal-crypto-exchange#16]
Create a Camunda process which will do the following:

1. Wait for user 1 to send BTC to the BTC account of the exchange.
2. Thereafter send a certain amount of USDT to USDT account of user 1.

**Comment by dptij** [comment]
The main process looks like this:

![btc_to_usdt_v1](https://user-images.githubusercontent.com/54589606/138053598-c3031fc3-9ee4-4b9c-96ed-06611f65b9ff.png)

In the `Wait for BTC to arrive in exchange's account` we call the following sub-process:

![waitForBtc](https://user-images.githubusercontent.com/54589606/138053715-c9b4ceaa-9078-4cc6-be94-8e96042e26a3.png)

**Comment by dptij** [comment]
This wallet object can be a [Singleton](https://www.baeldung.com/spring-bean-scopes).

**Comment by dptij** [comment]
https://bitcoin.stackexchange.com/questions/108324/bitcoinj-regtest-error-in-addwallet-transaction-fetch

**Comment by dptij** [comment]
* https://bitcoinj.org/getting-started-java#initial-setup
* https://github.com/bitcoinj/bitcoinj/blob/master/examples/src/main/java/org/bitcoinj/examples/ForwardingService.java

**Comment by dptij** [comment]
Next step: Ask the [question from StackOverflow](https://stackoverflow.com/questions/69764709/how-can-i-get-notified-when-money-has-been-sent-to-a-particular-bitcoin-address) in the [mailing list](https://groups.google.com/g/bitcoinj).

**Comment by dptij** [comment]
https://github.com/bitcoinj/bitcoinj/blob/master/examples/src/main/java/org/bitcoinj/examples/DoubleSpend.java

This example tries to do the same as you.

**Comment by mentiflectax** [comment]
There are no peers in BTC testnet according to http://localhost:3002/peers:

<img width="1329" alt="image" src="https://user-images.githubusercontent.com/1143055/140298740-dd97de10-4b4b-467f-9506-b83b4ccd9050.png">

**Comment by mentiflectax** [comment]
https://www.ulam.io/blog/how-to-setup-a-custom-bitcoin-testnet/

**Comment by mentiflectax** [comment]
https://btc4j.github.io/btc4j-daemon/

**Comment by mentiflectax** [comment]
* Try to enable bloom filtering in the Docker image which starts Bitcoin Core.
* Add the parameter `-peerbloomfilters` ([details](https://manpages.debian.org/unstable/bitcoind/bitcoind.1.en.html)) to the call of `bicoind` in [entrypoint.sh](https://github.com/ulamlabs/bitcoind-custom-regtest/blob/master/entrypoint.sh).
* Alternatively, add `peerbloomfilters=1` to [bitcoin.conf](https://github.com/ulamlabs/bitcoind-custom-regtest/blob/master/bitcoin.conf).

**Comment by mentiflectax** [comment]
Will now try out the recommendation from [this answer](https://stackoverflow.com/a/69906139/399457) in class `com.dpisarenko.minimalcryptoexchange.debug.BtcWalletObservationSpike`.

**Comment by mentiflectax** [comment]
Next steps:

1. Update the documentation (changing of the `peerbloomfilters` setting).
2. Make sure this detection of incoming transactions works in a Camunda process.

**Comment by mentiflectax** [comment]
Next step: https://stackoverflow.com/questions/70281710/how-to-access-comments-of-bitcoin-transactions-in-java

**Comment by dptij** [comment]
Asked the same question in the [BitcoinJ mailing list](https://groups.google.com/g/bitcoinj/c/0w2dA6OfrtM).

**Comment by mentiflectax** [comment]
[Article](https://greg.jeanmart.me/2019/08/20/manage-erc20-tokens-in-java-with-web3j/) on how to interact with ERC20 in Java.

**Comment by mentiflectax** [comment]
Next steps:

1. Learn to convert ETH to USDT (make sure there is USDT in the contract).
2. Create an exchange account in USDT.
3. Put some funds into the USDT exchange account.

**Comment by dptij** [comment]
How to add fixed supply to ERC20

https://docs.openzeppelin.com/contracts/3.x/erc20-supply

**Comment by mentiflectax** [comment]
Now the total supply is specified (see [FAQ](https://dpisarenko.com/mce/en/faq/) for details).

**Comment by mentiflectax** [comment]
https://inblockchainwetrust.medium.com/a-little-guide-on-ethereum-development-with-java-part-i-ef4b8ee4cf40

https://linuxtut.com/en/675f8cc2b7c4435d3c82/

https://medium.com/coinmonks/ethereum-blockchain-hello-world-smart-contract-with-java-9b6ae2961ad1

https://stackoverflow.com/questions/52028956/web3j-java-function-call-returns-empty-list-on-solidity-contract

https://www.baeldung.com/web3j

https://kauri.io/#communities/Java%20Ethereum/manage-erc20-tokens-in-java-with-web3j/

**Comment by mentiflectax** [comment]
Next step: Formulate conditions for the bounty for [this](https://stackoverflow.com/questions/70483315/why-am-i-getting-error-processing-transaction-request-intrinsic-gas-too-low-e) question.

**Comment by mentiflectax** [comment]
Next step: Change the USDT balance of the exchange by manipulating USDT balance as described [here](https://kndrck.co/posts/local_erc20_bal_mani_w_hh/).

**Comment by mentiflectax** [comment]
Go-ethereum [dev mode](https://geth.ethereum.org/docs/getting-started/dev-mode) may allow to get rid of gas-related problems.

**Comment by mentiflectax** [comment]
FYI:

1. Until today we had the following problem:

1.1. There was some ETH in the exchange account.
1.2. A USDT smart contract was deployed to the testnet.
1.3. The exchange account did not have any tUSDT.

2. The goal was to make sure that the exchange account has some USDT.

3. To find out how to do it, I asked this question on StackOverflow:

https://stackoverflow.com/questions/70483315/why-am-i-getting-error-processing-transaction-request-intrinsic-gas-too-low-e

4. After a lot of fighting, I finally realized, how to make sure that the exchange account on the testnet has some USDT.

The USDT smart contract ( https://github.com/mentiflectax/minimal-crypto-exchange/blob/i16/erc20/npm-prj/contracts/USDT.sol ) is an ERC20 token (I took the ERC20 implementation from OpenZeppelin).

Until today, the USDT smart contract looked like this:

```
contract USDT is ERC20 {
     constructor(uint256 initialSupply) ERC20("Test Tether", "tUSDT") {
    	_mint(msg.sender, initialSupply);
    }
```

`_mint(msg.sender, initialSupply)` means that `initialSupply` of tUSDT was send to the account `msg.sender` (I assume it is some HardHat account).

Turns out, you can specify the target account as a parameter (`owner` in the code snippet below):

```
    constructor(address owner, uint256 initialSupply) ERC20("Test Tether", "tUSDT") {
    	_mint(owner, initialSupply);
    }
```

Then, in the deployment script ( https://github.com/mentiflectax/minimal-crypto-exchange/blob/i16/erc20/npm-prj/scripts/deploy.js ) I can specify who (what account) should get the tUSDT (`0x190FD61ED8fE0067f0f09EA992C1BF96209bab66` is the account of the exchange on the local testnet):

```
const usdt = await USDT.deploy("0x190FD61ED8fE0067f0f09EA992C1BF96209bab66", 1000000000000000);
```

Next step:

1. Continue to work on a process, where the user sends test BTC to the exchange and gets tUSDT in return.
2. One of the things that needs to be implemented is sending tUSDT to the user account and avoiding gas-related problems. While working on the issue from the question I found some ways to work around them.

**Comment by mentiflectax** [comment]
Implemented
