### ISSUE TITLE
Minimal USDT->BTC conversion process

### ISSUE THREAD

**Issue by mentiflectax** [mentiflectax/minimal-crypto-exchange#20]

**Comment by mentiflectax** [comment]
Next step: Find out how to send USDT to the exchange outside of the exchange (e. g. using HardHat).

**Comment by dptij** [comment]
Next step: Try out whether or not the explanation on [this page](https://ethereum.stackexchange.com/a/98731) works:

```
const MyContract = await ethers.getContractFactory("MyContract");
const contract = await MyContract.attach(
  "0x..." // The deployed contract address
);

// Now you can call functions of the contract
await contract.doTheThing();
```

**Comment by dptij** [comment]
Another thing to figure out: How can I detect in Java that an amount was sent to the exchange account?

 * [ERC20](https://github.com/web3j/web3j/blob/master/contracts/src/main/java/org/web3j/contracts/eip20/generated/ERC20.java) source code

Another potentially useful method:

```
 public Flowable<TransferEventResponse> transferEventFlowable(EthFilter filter) {
        return web3j.ethLogFlowable(filter).map(new io.reactivex.functions.Function<Log, TransferEventResponse>() {
            @Override
            public TransferEventResponse apply(Log log) {
                Contract.EventValuesWithLog eventValues = extractEventParametersWithLog(TRANSFER_EVENT, log);
                TransferEventResponse typedResponse = new TransferEventResponse();
                typedResponse.log = log;
                typedResponse._from = (String) eventValues.getIndexedValues().get(0).getValue();
                typedResponse._to = (String) eventValues.getIndexedValues().get(1).getValue();
                typedResponse._value = (BigInteger) eventValues.getNonIndexedValues().get(0).getValue();
                return typedResponse;
            }
        });
    }
```

 * [EthFilter](https://github.com/web3j/web3j/blob/master/core/src/main/java/org/web3j/protocol/core/methods/request/EthFilter.java)

But with the EthFilter we need to know the starting block.

**Comment by mentiflectax** [comment]
Now we can see the USDT balance before and after a manual step (`exchange_usdt_for_btc_process`).

Next step: Create a ETH account for the USDT sender.

**Comment by mentiflectax** [comment]
Next step: Add creation of USDT sender address in [this repository](https://github.com/mentiflectax/geth-poa-testnet/blob/master/entrypoint.sh).

**Comment by mentiflectax** [comment]
Now, it looks like both the exchange and the USDT sender has some USDT.

**Next step:** Find out how to send USDT outside of the exchange (USDT sender to the exchange).

**Comment by mentiflectax** [comment]
Next step: Fix the error described in [this question](https://stackoverflow.com/questions/70725078/how-to-diagnose-an-erc20-error-error-execution-reverted-on-a-local-testnet).

**Comment by dptij** [comment]
Next step: Send BTC programmatically

Potentially useful link: [1](https://bitcoin.stackexchange.com/questions/81376/how-do-i-sign-and-send-a-raw-transaction-using-bitcoinj)

**Comment by dptij** [comment]
[2](https://stackoverflow.com/questions/51785369/bitcoinj-send-payment-from-a-wallet)

[3](https://www.edureka.co/community/19020/bitcoinj-send-payment-from-a-wallet)

**Comment by mentiflectax** [comment]
```
USDT Tx
  
0x95bb61356aa4088d362dc8b5fea94db4cfef129c959134fcc543e8243b9f4769

BTC

2NDjv4EUtXxKpfHCMuTmNg4miU9QDqy8vKs


bitcoin-cli -regtest generatetoaddress 10 2N1akcbAa3oXJ7RNxrAWmL7ZuuU9iHg9tpG


How to create a wallet

bitcoin-cli -regtest createwallet "exchange" passphrase='these-pretzels-are-making-me-thirsty'


( disable_private_keys blank "passphrase" avoid_reuse descriptors load_on_startup )


https://livebook.manning.com/book/grokking-bitcoin/a-using-bitcoin-cli/v-6/1

https://developer.bitcoin.org/reference/rpc/createwallet.html

vessel federal unveil express announce umbrella artefact notable curve minimum athlete void

Password:

these-pretzels-are-making-me-thirsty


bitcoin-cli -regtest generatetoaddress 10 bcrt1qwyrwqsq6wf862upqqavckww35wc2t20jckmnpe

```

**Comment by mentiflectax** [comment]
Next step: Create a wallet on regtest network which we can use to send test BTC.

**Comment by mentiflectax** [comment]
* https://developpaper.com/how-to-generate-bitcoin-wallet-address-in-java/
 * https://bitcoinj.org/getting-started-java
 * https://metamug.com/article/security/java-generate-bitcoin-wallet-address.html
 * https://medium.com/programmers-blockchain/creating-your-first-blockchain-with-java-part-2-transactions-2cdac335e0ce
 * https://medium.com/@parthshah.ce/generate-bitcoin-addresses-using-java-in-six-steps-b1c418796a9e
 * https://www.novixys.com/blog/generate-bitcoin-addresses-java/
 * https://github.com/MultiChain/sample-bitcoinj/blob/master/core/src/main/java/org/bitcoinj/core/Wallet.java

**Comment by mentiflectax** [comment]
Next step: Ask on SO how to create a wallet using `bitcoin-cli` or bicoinj so that it can be used in the sending delegate.

**Comment by dptij** [comment]
Here is the [question](https://bitcoin.stackexchange.com/questions/111913/how-to-create-a-bitcoin-walled-on-a-local-testnet-using-bitcoin-cli).

**Comment by dptij** [comment]
Idea: Look at the source code of Bitcoin Core (bitcoin-cli) and find out how wallets are created there.

**Comment by dptij** [comment]
Maybe we can add this code into

 * [entrypoint.sh](https://github.com/ulamlabs/bitcoind-custom-regtest/blob/master/entrypoint.sh) or
 * [mining.sh](https://github.com/ulamlabs/bitcoind-custom-regtest/blob/master/mining.sh).

**Comment by dptij** [comment]
Idea: `dumpprivkey` would return the private key for a particular address [Source](https://en.bitcoin.it/wiki/Original_Bitcoin_client/API_calls_list)

**Comment by dptij** [comment]
Idea: `createwallet "wallet_name" ( disable_private_keys blank "passphrase" avoid_reuse )`, see https://coinguides.org/backup-core-wallet-restore-wallet-dat/

**Comment by dptij** [comment]
Next step: Try out the `dumpprivkey` option

 * https://bitcoincore.org/en/doc/0.16.0/rpc/wallet/dumpprivkey/
 * https://www.quora.com/How-do-I-get-my-private-key-with-bitcoin-core

**Comment by dptij** [comment]
Try out this:

```
bitcoin-cli dumpprivkey "myaddress"

bitcoin-cli importprivkey "mykey"

curl --user myusername --data-binary '{"jsonrpc": "1.0", "id": "curltest", "method": "dumpprivkey", "params": ["myaddress"]}' -H 'content-type: text/plain;' http://127.0.0.1:8332/


```

Source: https://developer.bitcoin.org/reference/rpc/dumpprivkey.html

**Comment by dptij** [comment]
Idea: Diagonally read "Mastering Bitcoin" to find out how to create a wallet on the command line.

**Comment by dptij** [comment]
https://www.tabnine.com/web/assistant/code/rs/5c785067df79be0001e50aa4#L128

**Comment by dptij** [comment]
https://www.programcreek.com/java-api-examples/?api=org.bitcoinj.kits.WalletAppKit

**Comment by mentiflectax** [comment]
Another dirty hack idea: Run a command-line command from Java to send the Bitcoin.

**Comment by mentiflectax** [comment]
That's the command: `bitcoin-cli sendtoaddress "2NDjv4EUtXxKpfHCMuTmNg4miU9QDqy8vKs" 0.1` where `2NDjv4EUtXxKpfHCMuTmNg4miU9QDqy8vKs` is the target address.

**Comment by mentiflectax** [comment]
Actually, this one is better: `docker exec -it minimal-crypto-exchange_node_1 bitcoin-cli sendtoaddress "2NDjv4EUtXxKpfHCMuTmNg4miU9QDqy8vKs" 0.1`

**Comment by mentiflectax** [comment]
Next step: Figure out how to submit Docker commands from Java:

https://stackoverflow.com/questions/70801862/how-to-execute-a-docker-command-under-macos-from-java

**Comment by mentiflectax** [comment]
Next step: Write automated tests for the USDT->BTC exchange process.

**Comment by mentiflectax** [comment]
Implemented.
